### ISSUE TITLE
Use Regex captures in replace

### ISSUE THREAD

**Issue by kardeiz** [dalance/amber#10]
Sorry if I missed this in the docs...

Is it possible to use a regex capture with `ambr`?

For example, I want to do something like:

    ambr --regex 'This is your (.*)' 'This is my \1'

I've tried '\1', '$1', as well as named captures, but those don't work.

**Comment by Boscop** [comment]
Thanks, I'm also looking forward to this feature :)

**Comment by Boscop** [comment]
The [`rnr` tool](https://github.com/ChuckDaniels87/rnr) for file/folder renaming supports renames with `$n` syntax and named groups with `(?P<name>expr)` and `${name}`.
I'd prefer if amber supports it the same way. (I think this is the standard way of the regex crate.)

**Comment by kardeiz** [comment]
@Boscop at least in the regex crate the curly brackets are optional for named captures (e.g., `$ext` would be fine here). I would suggest just following how the regex crate handles them.

**Comment by dalance** [comment]
@Boscop @kardeiz 
I implemented regex capture, and released v0.5.0.

**Comment by kardeiz** [comment]
@dalance Awesome, works great!
