### ISSUE TITLE
"--" replacement string seen as an argument flag

### ISSUE THREAD

**Issue by bburdette** [dalance/amber#202]
I wanted to search and replace to comment out some code in elm, where comments start with `--`.  But looks like ambr interprets that as an argument, even though its in quotes.

```
[bburdette@HOSS:~/code/bis-kit/web/elm/src]$ ambr "import TangoColors as TC" "-- import TangoColors as TC"
error: Found argument '-- import TangoColors as TC' which wasn't expected, or isn't valid in this context
```

**Comment by danopia** [comment]
I believe the common CLI method of safely using `--` in your arguments is by adding a `--` before the positional arguments, e.g.:

`ambr -- "import TangoColors as TC" "-- import TangoColors as TC"`

Does this feel satisfactory?

**Comment by bburdette** [comment]
Feels weird to be honest!  But probably better to have it work in a way that's consistent with other bash tools.
