### ISSUE TITLE
Suggestion: Show line number in ambr, when stepping through the matches

### ISSUE THREAD

**Issue by Boscop** [dalance/amber#21]
Suggestion: Show line number in ambr, when stepping through the matches.

**Comment by dalance** [comment]
ambr supports `--column` option like below:

```
$ ambr --column version version2
./src/ambr.rs: 23:#[structopt(raw(long_version = "option_env!(\"LONG_VERSION\").unwrap_or(env!(\"CARGO_PKG_VERSION\"))"))]
```

**Comment by Boscop** [comment]
Ah thanks, I didn't that, I'll try it.
But it would be useful to show the line numbers by default to at least give a little context.

**Comment by dalance** [comment]
I added config support.
If there is `~/.ambr.toml` like below, showing line number becomes default.

```toml
column = true
```
