### ISSUE TITLE
ambr: "Replace keyword? [Y]es/[n]o/[a]ll/[q]uit:" Enter does nothing

### ISSUE THREAD

**Issue by Boscop** [dalance/amber#22]
In ambr, when stepping through the matches, it shows `Replace keyword? [Y]es/[n]o/[a]ll/[q]uit:`. To me, the capitalized `Y` means that if I press enter, it will mean the same as `Y`. But when I press enter, nothing happens, it just shows the same prompt again!

**Comment by dalance** [comment]
Enter was detected by '\n' only. I added '\r' to detect enter.
Could you try the latest revision of master branch?

**Comment by Boscop** [comment]
Thanks, I'll try it when I'm on my Windows PC again. Btw, yes, this happened on Windows.
