### ISSUE TITLE
Terminal settings not cleaned up on exit

### ISSUE THREAD

**Issue by Nudin** [dalance/amber#30]
I do the following:
- `$ ambr foo bar`
- Press `q` to quit
and then when I type in bash everything I type is invisible and the terminal behaves "weird" in a lot of ways. Only after blindly typing `stty sane` every is back to normal.

`stty` shows the following setting that where not there before calling amber:
```
min = 1; time = 0;
-icanon -echo
```

I'm using the current git-version install on Arch by the AUR package.

**Comment by dalance** [comment]
Thank you for your report.
I tried to reproduce the issue, but it was not reproduced.
Could you describe your environment (ex. OS, terminal, shell,,,) ?

**Comment by Nudin** [comment]
bash, kitty, Arch-Linux

**Comment by Nudin** [comment]
Just tested with other terminals (Konsole & xterm) and I get the same issue there.

**Comment by Nudin** [comment]
`bash --norc --noprofile` also does not fix the issue.

**Comment by dalance** [comment]
Thanks!
I fixed it. Could you try current master branch?

**Comment by Nudin** [comment]
Works! Thank you a lot for the super fast fix and for amber in general!
