### ISSUE TITLE
Use relative path in output

### ISSUE THREAD

**Issue by jaredramirez** [dalance/amber#31]
Thanks for the great tool!

When running either `ambs` or `ambr` specifying a path, it shows the fully qualified path.

`abmr createShipment cs js/test`:
<img width="1372" alt="Screen Shot 2020-04-10 at 14 37 51" src="https://user-images.githubusercontent.com/8095741/79024820-f068b380-7b38-11ea-90e9-2eaee847205f.png">
`ambs createShipment js/tests`:
<img width="1612" alt="Screen Shot 2020-04-10 at 14 37 36" src="https://user-images.githubusercontent.com/8095741/79024824-f2327700-7b38-11ea-8ae9-1834b296dace.png">

The directory I'm in when I ran the both commands was `/Users/jaredramirez/dev/github.com/replenysh/replenysh-backend/`. It would save a lot of space and make the resulting search/replace be easier to interpret if `ambs`/`ambr` would only show `./js/tests/lib/_.js` when the specified path is in the current directory

**Comment by dalance** [comment]
Thanks!
I fixed this issue, and released v0.5.4.

**Comment by jaredramirez** [comment]
Awesome, thanks so much!
