### ISSUE TITLE
remove

### ISSUE THREAD

**Issue by ShalokShalom** [dalance/amber#318]
Hi there :)

I would like to remove word/line, is this possible currently?

doc shows nothing on a first glance

**Comment by Yingrjimsch** [comment]
@ShalokShalom if I want to remove a word I just do `ambr WORD ""` replacing the word with nothing. To remove a line you should be able to do the same `ambr --regex "\nLINE" ""`

**Comment by ShalokShalom** [comment]
thanks a lot
