### ISSUE TITLE
Consider using `ignore` crate

### ISSUE THREAD

**Issue by beeb** [dalance/amber#337]
Would you consider using the [ignore](https://crates.io/crates/ignore) crate for ignoring files found in `.gitignore` and more?

That would increase the feature set (I see in https://github.com/dalance/amber/issues/2 that some patterns are not supported) and reduce the maintainability burden on this project.

If this is something that would be acceptable, I could probably work on a PR for this.

**Comment by dalance** [comment]
Thank you for your suggestion.
I can accept it.

**Comment by beeb** [comment]
Started implementing here https://github.com/dalance/amber/pull/341

It was extremely simple, but I want to compare performance, however I don't have access to the benchmark data.

**Comment by dalance** [comment]
Benchmark data of README.md is the result of https://github.com/dalance/amber/blob/master/compare_ambr.sh.
I think pattern1 and pattern2 is suitable to this comparison because they include many files and `.gitignore`.
The comparison can be executed like below:

```
$ git clone https://github.com/torvalds/linux data/linux
$ hyperfine --warmup 3 "./target/release/ambs EXPORT_SYMBOL_GPL ./data/linux" "ambs EXPORT_SYMBOL_GPL ./data/linux"
$ hyperfine --warmup 3 "./target/release/ambs irq_bypass_register_producer ./data/linux" "ambs irq_bypass_register_producer ./data/linux"
```

**Comment by beeb** [comment]
Thanks! I added the results to the PR and it's now ready for review.
