### ISSUE TITLE
Ability to preserve timestamps

### ISSUE THREAD

**Issue by ngirard** [dalance/amber#34]
Hi,

for some of the sets of files I'm working with, the files' mtime is important.
But when I need to perform some refactoring with them, I want their timestamps to be preserved.

I'm familiar with the other modern search & replacement tools (namely [Fastmod](https://github.com/facebookincubator/fastmod) and [Ruplacer](https://github.com/TankerHQ/ruplacer)), and oddly enough none of them offers this feature.

Therefore, I'd be much interested if Amber implemented it.

Cheers, and thanks for your work !

**Comment by dalance** [comment]
Thank you for your suggestion.
What do you think about atime?
I think the following plans.
Which is suitable for your use case?

1. adding two options

`--preserve-mtime`: preserve mtime only
`--preserve-atime`: preserve atime only

2. adding one option

`--preserve-time`: preserve mtime and atime

**Comment by ngirard** [comment]
Forgive me for my bad phrasing, which made you think that by timestamps I meant both mtime and atime.
I'm just concerned about the mtime, and I'm pretty sure it would be the same with most people.
The reason is, it's so I/O intensive to maintain access times that most often filesystems are mounted with the `noatime` option.
I'm confident it's the behaviour chosen by most Linux distributions nowadays.

I'd thus suggest to simply ignore the access time.

**Comment by dalance** [comment]
I added `--preserve-time` option, and released v0.5.5.

**Comment by ngirard** [comment]
Wow, thanks very much ! I haven't tested it yet.

**Comment by ngirard** [comment]
Working like a charm... closing as fixed. Thanks again !
