### ISSUE TITLE
Err… Error?

### ISSUE THREAD

**Issue by sergeevabc** [dalance/amber#75]
Windows 7, ambr 0.5.8

``` console
$ ambr.exe -r ">\.\.\b" ">..."
thread 'replacer' panicked at 'called `Option::unwrap()` on a `None` value', src\pipeline_replacer.rs:222:45 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                
```

**Comment by dalance** [comment]
Thank you for your report.
`\b` may be the cause of problem. I'll investigate it.

https://github.com/rust-lang/regex/issues/755

**Comment by dalance** [comment]
I fixed it, and released v0.5.9.

**Comment by sergeevabc** [comment]
It seems Amber, being Rust-related app, is also affected by [greedy/non-greedy issue][1].
But, frankly saying, what’s truly annoying is the lack of file-based support, e.g. `*.md` won’t work.  

[1]: https://github.com/nevdelap/ned/issues/55#issuecomment-812204043

**Comment by nevdelap** [comment]
> It seems Amber, being Rust-related app, is also affected by [greedy/non-greedy issue](https://github.com/nevdelap/ned/issues/55#issuecomment-812204043).
> But, frankly saying, what’s truly annoying is the lack of file-based paths, e.g. `*.md` won’t work.

The problem isn't with Rust apps Aleksander, the problem is with your Windows app - it is doing the wrong thing.
