### ISSUE TITLE
Question: Difference between ripgrep and fastmod?

### ISSUE THREAD

**Issue by pickfire** [dalance/amber#8]
Amber looks cool but what is the difference between ambs and [rg][r] as well as ambr and [fastmod][f]?

It would be cool as well to include benchmark for [rg][r]. And [hyperfine][h] could be used for benchmark.

[r]: https://github.com/BurntSushi/ripgrep
[f]: https://github.com/facebookincubator/fastmod
[h]: https://github.com/sharkdp/hyperfine

**Comment by dalance** [comment]
Thank you for your suggestion.
I updated benchmark results with hyperfine.

rg/fastmod is fast in the case of many files,
and amber has advantage in the case of large file search.

**Comment by pickfire** [comment]
Nice, cool to see the benchmark. I am surprised that amber seems faster here. Maybe @BurntSushi might be interested in this.

**Comment by dalance** [comment]
@BurntSushi 
Thank you for your comment.
Currently amber show line by match. So the line matched repeatedly is duplicated.
I'll fix it, and try `regex::bytes::Regex`.
